### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [lockatme/lockatme#16]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by sweenu** [comment]
Hello @mansya, that is a very nice offer! I don't quite know what the future is for this project but I would be glad to have a logo :)

**Comment by mansya** [comment]
hi sir. I have designed the logo for this project. How ? do you like it ? if yes please inform me. and if there is a change please tell me.
![1](https://user-images.githubusercontent.com/33461607/49305086-d492dd80-f500-11e8-8ce1-ef1f1b215273.png)
![s](https://user-images.githubusercontent.com/33461607/49306044-9fd45580-f503-11e8-9d51-bfde7613b9a3.jpg)

**Comment by mansya** [comment]
hi sir. how about this offer? are you interested ?
